// Octopus Pet — per-scene spritesheet metadata, generated by scripts/generate-spritesheet-manifest.sh
// Source: app/public/assets/octopus/spritesheet-manifest.json
//
// Copied into src/ at build time via Vite's resolveJsonModule (vite-env.d.ts).
// The actual JSON is fetched from /public/assets/octopus/spritesheet-manifest.json
// in the running app — this file just declares the type for code that uses it.

import type { OctopusScene } from "./types";

export interface SceneMeta {
  sceneId: OctopusScene;
  dirName: string;
  fileName: string;
  fileSize: number;
  exists: boolean;
  cols: number;
  rows: number;
  frameCount: number;
  width: number;
  height: number;
  alphaMode: "RGB" | "RGBA";
}

export interface SpritesheetManifest {
  $schema: string;
  version: string;
  generatedAt: string;
  cellSize: number;
  defaultFrameCount: number;
  defaultRows: number;
  defaultCols: number;
  webpMaxDim: number;
  format: string;
  scenes: SceneMeta[];
  totalSize: number;
  sceneCount: number;
}

/** Returns SceneMeta for a given scene id, or throws. */
export function getSceneMeta(manifest: SpritesheetManifest, scene: OctopusScene): SceneMeta {
  const m = manifest.scenes.find((s) => s.sceneId === scene);
  if (!m) {
    throw new Error(`Scene not found in manifest: ${scene}`);
  }
  return m;
}

/** Public URL for a scene's spritesheet. */
export function getSpritesheetUrl(scene: OctopusScene, manifest: SpritesheetManifest): string {
  return `/assets/octopus/${getSceneMeta(manifest, scene).fileName}`;
}

/** Map frame index → (col, row) in the grid. */
export function frameToGrid(
  frame: number,
  meta: SceneMeta,
): { col: number; row: number } {
  const col = frame % meta.cols;
  const row = Math.floor(frame / meta.cols);
  return { col, row };
}
