// AUTO-GENERATED from scenes.json by scripts/build_scene_registry.py.
// DO NOT EDIT — re-run the script after editing scenes.json.


/** Scene ids exposed to MCP `pet_list_states` and validated by `pet_show`. */
pub static SCENES: &[&str] = &[
    "detective-study",
    "worker-construction",
    "drink-coffee",
    "breakdown",
    "friday-5pm",
    "pretend-busy",
    "stay-late",
    "treat-milk-tea",
    "13-debug-snack",
    "16-deadline-sprint",
    "17-celebrate",
    "18-monday-morning",
    "19-thumbs-up",
    "20-thinking",
    "22-yay-friday",
    "23-dancing",
    "24-surprised",
    "29-shy",
    "30-wave",
    "31-apologize",
    "32-laugh",
    "33-magic",
    "34-meditation",
    "35-blink",
    "36-cheer",
    "payday",
];

/** Bubble lines per scene — surfaced for diagnostics / future use. */
pub static BUBBLE_LINES: &[(&str, &[&str])] = &[
    ("detective-study", &["在研究", "放大看看", "找到了", "等一下", "认真脸", "让我看看...", "用户不好糊弄"]),
    ("worker-construction", &["施工中", "砸一下", "放桌子", "建好了", "戴好安全帽", "让我想想...", "我摸鱼应该不会被发现"]),
    ("drink-coffee", &["喝咖啡", "好香啊", "续杯吗", "今日份咖啡", "早八续命", "摸鱼时间", "让我清醒一下"]),
    ("breakdown", &["抱头", "撑不住", "我裂了", "不行了", "想下班", "累死了", "救救我"]),
    ("friday-5pm", &["跑了", "起飞", "下班咯", "冲鸭", "周末啦", "自由了", "收工"]),
    ("pretend-busy", &["忙死了", "别烦", "敲键盘", "好累", "加班中", "努力搬砖", "假装"]),
    ("stay-late", &["叹气", "好累", "加班中", "想家", "撑住", "摸鱼", "躺平"]),
    ("treat-milk-tea", &["喝奶茶", "好喝", "续杯", "奶茶", "吨吨吨", "加糖", "放松"]),
    ("13-debug-snack", &["解bug", "吃点啥", "薯片", "可乐", "嘴馋", "再来一口", "真香"]),
    ("16-deadline-sprint", &["还有1h", "救命", "加快", "赶DDL", "要死了", "来不及", "冲刺"]),
    ("17-celebrate", &["完成", "耶", "庆祝", "撒花", "撒彩", "搞定", "欢呼"]),
    ("18-monday-morning", &["周一", "再睡5分钟", "不想起", "好困", "闹钟响", "挣扎", "罢工"]),
    ("19-thumbs-up", &["棒", "不错", "好赞", "可以", "认可", "确认", "顶你"]),
    ("20-thinking", &["想想", "思考", "嗯", "让我想想", "有点难", "该怎么办", "也许"]),
    ("22-yay-friday", &["周五", "下班啦", "干杯", "走起", "起飞", "周末", "cheers"]),
    ("23-dancing", &["跳", "动次", "蹦迪", "音乐", "律动", "撒欢", "嗨起来"]),
    ("24-surprised", &["啥", "惊", "什么鬼", "真的假的", "哇", "哦豁", "震惊"]),
    ("29-shy", &["害羞", "好害臊", "别看", "脸红", "捂脸", "甜", "诶嘿"]),
    ("30-wave", &["嗨", "你好", "过来", "招呼", "挥手", "好久不见", "哟"]),
    ("31-apologize", &["抱歉", "对不起", "我错", "求原谅", "别生气", "呜呜", "sorry"]),
    ("32-laugh", &["哈哈", "笑死", "太逗", "笑哭", "哈哈哈", "逗我呢", "笑"]),
    ("33-magic", &["魔法", "变", "惊喜", "奇迹", "看我", "bilibala", "奇迹时刻"]),
    ("34-meditation", &["安静", "深呼吸", "冥想", "心静", "放松", "禅", "om"]),
    ("35-blink", &["眨", "干嘛", "嗯", "看我", "眨眼", "啥事", "等下"]),
    ("36-cheer", &["加油", "冲鸭", "go", "we are", "胜利", "团队", "齐心"]),
    ("payday", &["发薪", "有钱", "爽", "money", "收钱", "豪", "撒钱"]),
];
